monitor.alsa.rules = [
  {
    matches = [
      { node.name = "~alsa_output.*Samsung.*" }
      { node.name = "~alsa_input.*Samsung.*" }
    ]
    actions = {
      update-props = {
        audio.format = "S16_LE"
        api.alsa.period-size = 1024
        api.alsa.headroom = 8192
      }
    }
  }
]
