monitor.alsa.rules = [
  {
    matches = [
      { node.name = "~alsa_output.*Samsung.*" }
    ]
    actions = {
      update-props = {
        audio.format           = "S32_LE"
        api.alsa.period-size   = 960
        api.alsa.headroom      = 8192
      }
    }
  }
  {
    matches = [
      { node.name = "~alsa_input.*Samsung.*" }
    ]
    actions = {
      update-props = {
        audio.format           = "S16_LE"
        api.alsa.period-size   = 960
        api.alsa.headroom      = 1024
      }
    }
  }
]
